### ISSUE TITLE
Readme compile guidance miskate

### ISSUE THREAD

**Issue by sujoshua** [LittlenineLst/android_kernel_samsung_sm8650_KSU#1]
> Plz run ./setup.sh to start compiling the kernel

There is no `setup.sh` but `build.sh`. Can you double-check which file you mean? Thanks.

---
没看见`setup.sh`在哪里诶，指的是`build.sh`吗？我只看见了那个。想学习一下如何编译内核。谢啦

**Comment by LittlenineEnnea** [comment]
Oh, Its build.sh , im sorry for that

**Comment by LittlenineEnnea** [comment]
> > Plz run ./setup.sh to start compiling the kernel
> 
> There is no `setup.sh` but `build.sh`. Can you double-check which file you mean? Thanks.
> 
> 没看见`setup.sh`在哪里诶，指的是`build.sh`吗？我只看见了那个。想学习一下如何编译内核。谢啦

Thanks, ive changed that
